---
# tasks file for ansible-role-crontab-security

- name: "Ensure group crontab exists"
  ansible.builtin.group:
    name: "{{ crontab_group }}"
    state: present

- name: "Test for existence /etc/crontab"
  ansible.builtin.stat:
    path: /etc/crontab
  register: file_exists

- name: "Ensure appropriate permission and owner is configured for /etc/crontab"
  ansible.builtin.file:
    path: /etc/crontab
    owner: root
    group: root
    mode: '0600'
    state: file
  when:
    - file_exists.stat is defined
    - file_exists.stat.exists

- name: "Test for existence /etc/cron.hourly"
  ansible.builtin.stat:
    path: /etc/cron.hourly
  register: folder_exists

- name: "Ensure appropriate permission and owner is configured for /etc/cron.hourly"
  ansible.builtin.file:
    path: /etc/cron.hourly
    owner: root
    group: root
    mode: '0700'
    state: directory
  when:
    - folder_exists.stat is defined
    - folder_exists.stat.exists

- name: "Test for existence /etc/cron.daily"
  ansible.builtin.stat:
    path: /etc/cron.daily
  register: folder_exists

- name: "Ensure appropriate permission and owner is configured for /etc/cron.daily"
  ansible.builtin.file:
    path: /etc/cron.daily
    owner: root
    group: root
    mode: '0700'
    state: directory
  when:
    - folder_exists.stat is defined
    - folder_exists.stat.exists

- name: "Test for existence /etc/cron.weekly"
  ansible.builtin.stat:
    path: /etc/cron.weekly
  register: folder_exists

- name: "Ensure appropriate permission and owner is configured for /etc/cron.weekly"
  ansible.builtin.file:
    path: /etc/cron.weekly
    owner: root
    group: root
    mode: '0700'
    state: directory
  when:
    - folder_exists.stat is defined
    - folder_exists.stat.exists

- name: "Test for existence /etc/cron.monthly"
  ansible.builtin.stat:
    path: /etc/cron.monthly
  register: folder_exists

- name: "Ensure appropriate permission and owner is configured for /etc/cron.monthly"
  ansible.builtin.file:
    path: /etc/cron.monthly
    owner: root
    group: root
    mode: '0700'
    state: directory
  when:
    - folder_exists.stat is defined
    - folder_exists.stat.exists

- name: "Test for existence /etc/cron.d"
  ansible.builtin.stat:
    path: /etc/cron.d
  register: folder_exists

- name: "Ensure appropriate permission and owner is configured for /etc/cron.d"
  ansible.builtin.file:
    path: /etc/cron.d
    owner: root
    group: root
    mode: '0700'
    state: directory
  when:
    - folder_exists.stat is defined
    - folder_exists.stat.exists

- name: "Remove /etc/at.deny file"
  ansible.builtin.file:
    path: /etc/at.deny
    state: absent

- name: "Test for existence /etc/at.allow"
  ansible.builtin.stat:
    path: /etc/at.allow
  register: file_exists

- name: "Set Fact for file_exists"
  ansible.builtin.set_fact:
    at_file_exists: '{{ file_exists.stat.exists }}'

- name: "Ensure appropriate permissio and owner is configured for /etc/at.allow"
  ansible.builtin.file:
    path: /etc/at.allow
    owner: root
    group: "{{ crontab_group }}"
    mode: '0640'
  when:
    - at_file_exists is defined
    - at_file_exists == true

- name: "Ensure appropriate permission, owner and content is configured for /etc/at.allow"
  ansible.builtin.copy:
    dest: /etc/at.allow
    owner: root
    group: "{{ crontab_group }}"
    mode: '0640'
    content: |
      root
  when:
    - at_file_exists is defined
    - at_file_exists != true

- name: "Remove /etc/cron.deny file"
  ansible.builtin.file:
    path: /etc/cron.deny
    state: absent

- name: "Test for existence /etc/cron.allow"
  ansible.builtin.stat:
    path: /etc/cron.allow
  register: file_exists

- name: "Set Fact for file_exists"
  ansible.builtin.set_fact:
    cron_file_exists: '{{ file_exists.stat.exists }}'

- name: "Ensure appropriate permission and owner is configured for /etc/cron.allow"
  ansible.builtin.file:
    path: /etc/cron.allow
    owner: root
    group: "{{ crontab_group }}"
    mode: '0640'
  when:
    - cron_file_exists is defined
    - cron_file_exists == true

- name: "Ensure appropriate permission, owner and content is configured for /etc/cron.allow"
  ansible.builtin.copy:
    dest: /etc/cron.allow
    owner: root
    group: "{{ crontab_group }}"
    mode: '0640'
    content: |
      root
  when:
    - cron_file_exists is defined
    - cron_file_exists != true
